### ISSUE TITLE
Modfiy code into realtime pose estimation.

### ISSUE THREAD

**Issue by peterx7803** [ARG-NCTU/text-pick-n-place-baseline#1]
- [x] 0-1. (WS transplant) GPU, Driver, CUDA, CuDNN, Matlab
- [x] 0-2. (WS transplant) librealsense
- [x] 1. FCN prediction msg type: each class has their own prediction map (Not taking the softmax output).
- [x] 2. Adding feature: we could specify which classes we want from all prediction map.
- [x] 3. 6D pose visualization in Rviz

**Comment by peterx7803** [comment]
@yungshansu Please help librealsense v1 installation.
I am now checking where to modify in original code

**Comment by yungshansu** [comment]
OK, I am installing now

**Comment by yungshansu** [comment]
Ｄｏｎｅ

**Comment by yungshansu** [comment]
![screenshot from 2018-06-04 17-08-57](https://user-images.githubusercontent.com/13134697/40909748-e95635e4-681c-11e8-967e-b03fd7517834.png)

**Comment by yungshansu** [comment]
Thx :+1:

**Comment by peterx7803** [comment]
Now, I  could send a custom msg, it is  defined in marvin_convnet/msg/object_mask.msg. 
In this topic, you could get prediction probability map and this map is according to which object class.
